# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Kevin O'Connor
tagline:          'Software Engineer at large'
description:      "Software engineer at Google. I occasionally write about some of my <a href='https://github.com/kevinoconnor7'>side projects</a>."
url:              https://kevo.io
baseurl:          /

author:
  name:           "Kevin O'Connor"
  url:            https://kevo.io

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
