name: Deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build production site
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true
      - name: Build
        run: hugo -d _site --minify
      - name: Upload built site
        uses: actions/upload-artifact@v4
        with:
          name: built_site
          path: _site/
      - name: Upload github pages tar
        # Automatically uploads an artifact from the './_site' directory by default
        uses: actions/upload-pages-artifact@v3

  deploy-github:
    needs: build
    if: ${{ github.ref == 'refs/heads/master' }} # only run for master commits

    environment:
      name: github-pages
      url: ${{ steps.ghpages.outputs.page_url }}

    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: ghpages
        uses: actions/deploy-pages@v1

  deploy-aws:
    needs: build
    if: ${{ github.ref == 'refs/heads/master' }} # only run for master commits
    runs-on: ubuntu-latest
    steps:
      - name: Download built_site artifact
        uses: actions/download-artifact@v4
        with:
          name: built_site
          path: _site

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Sync output to S3
        run: |
          aws s3 sync ./_site/ s3://${{ secrets.S3_BUCKET }} --delete

      - name: Create Cloudfront invalidation
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DIST }} --paths "/*"
